apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-deploy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
	  nodePort: 31110
  type: NodePort