apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy
  template:
    metadata:
      labels:
        app: my-deploy
    spec:
      containers:
      - name: pod
        image: rajesh072/simple-react-calculator::simple-react-calculator-demo
        ports:
        - containerPort: 3000